### ISSUE TITLE
endless connections

### ISSUE THREAD

**Issue by valentin4ahif** [rstropek-teaching/real-time-game-quiz-4ahif-valentin4ahif#2]
If I start the server, everything is fine. But as soon as I start the client in the browser, endless connections are made till I close the browser-tab or till my computer freezes.
Me and some of my classmates puzzled already some hours but we couldn't find any errors.

Greetings, Valentin

**Comment by rstropek** [comment]
Hi @valentin4ahif 

I took a closer look at your source code. Is it the latest version? I am asking because there are some bugs in the code which prevent running and debugging it.

* First, *package.json* was incorrect. Therefore, NPM did not work at all. I corrected the bug and checked in the fix.

* *data.ts* contains a bunch of `export` keywords. Exporting members in JavaScript modules works fine on the server-side (Node.js). Without a tool like *system.js* or *webpack*, modules do not work in browsers (only Chrome supports them partly in its latest releases). My tip: Remove all the `export` keywords from *data.ts*.

* In * server.ts*, you setup `express.static` with the subdirectory name *public*. However, you do not have a subdirectory with that name. My tip: Either move all client-related artifacts into a *public* directory or use the root folder for static files (i.e. `app.use(express.static(__dirname));`).

* In *index.html*, you are referencing *jquery.min.js* (`<script src="jquery.min.js"></script>`). This reference cannot be found because of the previous issue (*public* subdirectory). Make sure jQuery can be found (e.g. changing code to `<script src="/node_modules/jquery/dist/jquery.min.js"></script>`).

* *login.html* is currently a fully fledged website. I don't think that is correct. You load *login.html* using jQuery's `load` method. Therefore, I recommend removing everything but the content of the body (i.e. remove `DOCTYPE`, `head`, `script` tags, `html`, and `body`).

* Make sure to use `commonjs` module format in *tsconfig.json*.

After these changes, the application can be opened in the browser without errors in the console. However, it does not work yet. I hope these tips help. If you fixed the bugs mentioned above and you still have problems with Websockets, do not hesitate to contact me again. I am happy to help.

Greetings,
Rainer Stropek.

**Comment by valentin4ahif** [comment]
I was very stressed when I wrote the issue, therefore I forgot make the _public_ folder in Github and just uploaded the files. Meaning, I had the _public_ folder on my local storage, but I just forgot to make it on Github too.
Now the latest version of my code is checked in.
My problem got solved by deleting the whole content of my _login.html_ file. Now my programm works just fine.

Thank you,
Valentin
